; You do not need to include every line or field. Each matching plugin completely replaces the built-in version embedded in the DLL. 
;
; ModNameTags=true/false
; Optional. When omitted or empty, defaults to true. Adds mod-name tags (e.g., (Little Library) or (Immersive College) tags).
;
; SkillTags=true/false
; Optional. When omitted or empty, defaults to true. Adds skill-related tags (e.g., (Restoration) or (Archery) tags).
;
; IncludeForms=FormID1,FormID2,FormID3
; Optional. When omitted or empty, all books are included.
; When populated, VBT tags ONLY the specified books.
;
; ExcludeForms=FormID1,FormID2,FormID3
; Optional. When omitted or empty, no books are excluded.
; When populated, VBT excludes the specified books.
;
; FormIDs may optionally use the 0x prefix.
; See sasnikol's "FormIDs and You":
; https://www.nexusmods.com/skyrimspecialedition/articles/6629
; Example valid FormIDs: 00000D6B, 0x00D6B, 0xD6B

[General]
; This controls whether any books are tagged at all.
Enabled=true

; This controls SkillTags GLOBALLY. Default: SkillTags=true
SkillTags=true

; This controls ModNameTags GLOBALLY. Default: ModNameTags=true
ModNameTags=true

; Default: GlobalPluginNameFallback=false
; GLOBAL: When true, automatically generates missing tags based on plugin filename.
GlobalPluginNameFallback=false

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;; Place custom rules below ;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This is just an example that has the optional plugin-specific fields:
[Plugin:ExampleModThatIHopeIsntReal2.esp]
Tag=Example Tag
ModNameTags=
SkillTags=
IncludeForms=
ExcludeForms=

; This is a simpler example. Adds (Simple Example) to all books from the specified plugin:
[Plugin:ExampleModThatIHopeIsntReal1.esp]
Tag=Simple Example
