; Each matching plugin section completely replaces the built-in version. You do not need to include every line/field.
;	ModNameTags=true/false
;		Line not present, or empty field, defaults to true. On/off switch for mod-name tags. (e.g., (Little Library) or (Immersive College) tags)
;	SkillTags=true/false
;		Line not present, or empty field, defaults to true. On/off switch for Skill tags. (e.g., (Restoration) or (Archery) tags)
;	IncludeForms=FormID1,FormID2, FormID3
;		Defaults to including all dialogue. Defaults if line not present, or empty field.
;		Entries will cause VBT to tag *only* the specified books. Spaces after commas in list are optional.
;	ExcludeForms=FormID1,FormID2, FormID3
;		Defaults to nothing being excluded. Defaults if line not present, or empty field.
;		Entries will cause VBT to exclude the specified books. Spaces after commas in list are optional.
;	You will need FormIDs for IncludeForms/ExcludeForms.
;		Please see sasnikol's "FormIDs and You" for general information regarding FormIDs: https://www.nexusmods.com/skyrimspecialedition/articles/6629

[General]
; Global rules. General on/off switches if you don't want certain features such as Skill tags.
Enabled=true
ModNameTags=true
SkillTags=true
GlobalPluginNameFallback=false
	; GlobalPluginNameFallback will automatically tag every book from every mod, using mod's plugin name if not explicitly tagged/supported in this INI or by VDT's embedded built-in rules.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;; Place custom rules below ;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; These two examples function the same; they will tag all books from/for specified mod:
[Plugin:ExampleModThatIHopeIsntReal1.esp]
Tag=Example Mod
ModNameTags=
SkillTags=
IncludeForms=
ExcludeForms=

; COPY THIS ONE FOR SIMPLICITY:
[Plugin:ExampleModThatIHopeIsntReal2.esp]
Tag=Example Mod 2

